{
 "title": "Daily Brew Infrastructure Monitoring",
 "refresh": "1m",
 "panels": [
  {
   "title": "Lambda Invocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "x": 0, "w": 12, "y": 0 },
   "targets": [
    {
     "region": "eu-west-1",
     "statistic": "Sum",
     "period": "300",
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "dimensions": { "FunctionName": "daily-brew-group-etl-lambda" }
    }
   ]
  },
  {
   "title": "Lambda Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "x": 12, "w": 12, "y": 0 },
   "targets": [
    {
     "region": "eu-west-1",
     "statistic": "Sum",
     "period": "300",
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "dimensions": { "FunctionName": "daily-brew-group-etl-lambda" }
    }
   ]
  },
  {
   "title": "Lambda Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "x": 0, "w": 12, "y": 8 },
   "targets": [
    {
     "region": "eu-west-1",
     "statistic": "Average",
     "period": "300",
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "dimensions": { "FunctionName": "daily-brew-group-etl-lambda" }
    }
   ]
  },
  {
   "title": "Grafana EC2 CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "x": 12, "w": 12, "y": 8 },
   "targets": [
    {
     "region": "eu-west-1",
     "statistic": "Average",
     "period": "300",
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "dimensions": { "InstanceId": "i-0e536ff505e427406" }
    }
   ]
  }
 ]
}